### PR TITLE
Fix minor comment issue

### PR DESCRIPTION
**Pull request by pfmooney**
An errant '`' was causing one part of the docs to render poorly.

### CODE REVIEW

**Review by dancrossnyc — APPROVED** [review]

**Comment by dancrossnyc** [comment]
The test failures seem to be due to `#![feature(...)]` mismatches, and entirely unrelated to this change, but are they expected?

**Review by bnaecker — APPROVED** [review]
Nice catch, thanks!

**Comment by bnaecker** [comment]
@dancrossnyc No, those aren't expected. I'm looking into it now.

**Comment by bnaecker** [comment]
See #41 for details on the test failures.

**Pull request merged**
